# Data Inspection and Cleaning

## import and setup

In [42]:
import pandas as pd
import numpy as np
import yaml
from pathlib import Path

In [43]:
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

## data load and column rename

In [44]:
df = pd.read_csv('../data/raw/incident_event_log.csv')

In [45]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,sys_created_by,sys_created_at,sys_updated_by,sys_updated_at,contact_type,location,category,subcategory,u_symptom,cmdb_ci,impact,urgency,priority,assignment_group,assigned_to,knowledge,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 21,29/2/2016 01:23,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 642,29/2/2016 08:53,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 804,29/2/2016 11:29,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 908,5/3/2016 12:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,Created by 171,29/2/2016 04:57,Updated by 746,29/2/2016 04:57,Phone,Location 165,Category 40,Subcategory 215,Symptom 471,?,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 89,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00

In [46]:
schema = yaml.safe_load(open('../configs/schema.yaml'))
schema_col = schema['raw_to_canonical']

In [47]:
schema['timestamp_cols']

['opened_timestamp',
 'creator_timestamp',
 'update_timestamp',
 'resolved_timestamp',
 'closed_timestamp']

In [48]:
df = df.rename(columns=schema_col)

In [49]:
df.head()

,case_id,case_status,is_open,reassigment_total,reopen_total,system_update_count,met_deadline,affected_user_id,reporter_user_id,opened_timestamp,creator_agent_id,creator_timestamp,update_agent_id,update_timestamp,contact_channel,location_id,categoryw,subcategory,issue_type_id,asset_id,impact_level,urgency_level,computed_priority_level,assigned_team_id,assigned_agent_id,used_knowledge_base,priority_confirmed,notify_email,issue_id,change_request_id,vendor_id,caused_by_ref_id,resolution_id,resolved_by_agent_id,resolved_timestamp,closed_timestamp
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 21,29/2/2016 01:23,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 642,29/2/2016 08:53,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 804,29/2/2016 11:29,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 908,5/3/2016 12:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,?,2 - Medium,2 - Medium,3 - Moderate,Group 56,?,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,Created by 171,29/2/2016 04:57,Updated by 746,29/2/2016 04:57,Phone,Location 165,Category 40,Subcategory 215,Symptom 471,?,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 89,True,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00

In [50]:
# replace missing values "?" with NaN
df = df.replace(schema.get("missing_values").get('token'), np.nan)

In [51]:
df.head()

,case_id,case_status,is_open,reassigment_total,reopen_total,system_update_count,met_deadline,affected_user_id,reporter_user_id,opened_timestamp,creator_agent_id,creator_timestamp,update_agent_id,update_timestamp,contact_channel,location_id,categoryw,subcategory,issue_type_id,asset_id,impact_level,urgency_level,computed_priority_level,assigned_team_id,assigned_agent_id,used_knowledge_base,priority_confirmed,notify_email,issue_id,change_request_id,vendor_id,caused_by_ref_id,resolution_id,resolved_by_agent_id,resolved_timestamp,closed_timestamp
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 21,29/2/2016 01:23,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 642,29/2/2016 08:53,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 804,29/2/2016 11:29,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,Created by 6,29/2/2016 01:23,Updated by 908,5/3/2016 12:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,Created by 171,29/2/2016 04:57,Updated by 746,29/2/2016 04:57,Phone,Location 165,Category 40,Subcategory 215,Symptom 471,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 89,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00

In [52]:
dayfirst = schema.get("parsing", {}).get("timestamp_day_first", True)

In [53]:
schema.get('timestamp_cols')

['opened_timestamp',
 'creator_timestamp',
 'update_timestamp',
 'resolved_timestamp',
 'closed_timestamp']

In [54]:
# timestamps as datetimes with day-first
for c in schema.get('timestamp_cols'):
    df[c] = pd.to_datetime(df[c], errors="coerce", dayfirst=dayfirst)

In [55]:
df.head()

,case_id,case_status,is_open,reassigment_total,reopen_total,system_update_count,met_deadline,affected_user_id,reporter_user_id,opened_timestamp,creator_agent_id,creator_timestamp,update_agent_id,update_timestamp,contact_channel,location_id,categoryw,subcategory,issue_type_id,asset_id,impact_level,urgency_level,computed_priority_level,assigned_team_id,assigned_agent_id,used_knowledge_base,priority_confirmed,notify_email,issue_id,change_request_id,vendor_id,caused_by_ref_id,resolution_id,resolved_by_agent_id,resolved_timestamp,closed_timestamp
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,2016-02-29 01:16:00,Created by 6,2016-02-29 01:23:00,Updated by 21,2016-02-29 01:23:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,2016-02-29 11:29:00,2016-03-05 12:00:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,2016-02-29 01:16:00,Created by 6,2016-02-29 01:23:00,Updated by 642,2016-02-29 08:53:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,2016-02-29 11:29:00,2016-03-05 12:00:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,2016-02-29 01:16:00,Created by 6,2016-02-29 01:23:00,Updated by 804,2016-02-29 11:29:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,2016-02-29 11:29:00,2016-03-05 12:00:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,2016-02-29 01:16:00,Created by 6,2016-02-29 01:23:00,Updated by 908,2016-03-05 12:00:00,Phone,Location 143,Category 55,Subcategory 170,Symptom 72,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 56,NaN,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,2016-02-29 11:29:00,2016-03-05 12:00:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,2016-02-29 04:40:00,Created by 171,2016-02-29 04:57:00,Updated by 746,2016-02-29 04:57:00,Phone,Location 165,Category 40,Subcategory 215,Symptom 471,NaN,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 89,True,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 81,2016-03-01 09:52:00,2016-03-06 10:00:00

In [56]:
df.describe()

,reassigment_total,reopen_total,system_update_count,opened_timestamp,creator_timestamp,update_timestamp,resolved_timestamp,closed_timestamp
count,141712.000000,141712.000000,141712.000000,141712,88636,141712,138571,141712
mean,1.104197,0.021918,5.080946,2016-04-12 22:19:09.100852736,2016-04-08 16:21:18.906539008,2016-04-19 10:49:49.286863616,2016-04-24 04:55:32.415873280,2016-04-29 23:48:41.171248640
min,0.000000,0.000000,0.000000,2016-02-29 01:16:00,2016-02-29 01:23:00,2016-02-29 01:23:00,2016-02-29 09:04:00,2016-02-29 17:47:00
25%,0.000000,0.000000,1.000000,2016-03-16 15:24:00,2016-03-14 16:13:00,2016-03-24 08:36:45,2016-03-25 09:17:30,2016-03-31 09:59:00
50%,1.000000,0.000000,3.000000,2016-04-07 16:27:00,2016-04-01 20:08:00,2016-04-13 11:06:00,2016-04-15 13:09:00,2016-04-20 13:07:00
75%,1.000000,0.000000,6.000000,2016-05-04 10:32:00,2016-04-28 16:43:00,2016-05-09 14:02:00,2016-05-12 12:36:00,2016-05-17 13:07:00
max,27.000000,8.000000,129.000000,2017-02-16 14:17:00,2017-01-27 16:59:00,2017-02-18 15:00:00,2017-02-17 00:47:00,2017-02-18 15:00:00
std,1.734673,0.207302,7.680652,NaN,NaN,NaN,NaN,NaN